/**
 * scripts/codegen.ts
 *
 * Reads data/faculties.json and data/departments.json and regenerates
 * packages/js/src/index.ts. Run this whenever the data files change.
 *
 * Usage: npx tsx scripts/codegen.ts
 */

import { readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

interface FacultyEntry {
  name: string;
  abbreviation: string;
}

interface DepartmentEntry {
  name: string;
  abbreviation: string;
  faculty: string;
}

const faculties: FacultyEntry[] = JSON.parse(
  readFileSync(resolve(root, "data/faculties.json"), "utf-8")
);

const departments: DepartmentEntry[] = JSON.parse(
  readFileSync(resolve(root, "data/departments.json"), "utf-8")
);

// ─── Validate data integrity before generating ────────────────────────────────

const facultyNames = new Set(faculties.map((f) => f.name));
const facultyAbbrevs = new Set(faculties.map((f) => f.abbreviation));
const deptAbbrevs = new Set<string>();

for (const dept of departments) {
  if (!facultyNames.has(dept.faculty)) {
    throw new Error(
      `Department "${dept.name}" references unknown faculty "${dept.faculty}"`
    );
  }
  if (deptAbbrevs.has(dept.abbreviation)) {
    throw new Error(
      `Duplicate department abbreviation "${dept.abbreviation}" on "${dept.name}"`
    );
  }
  deptAbbrevs.add(dept.abbreviation);
}

if (facultyAbbrevs.size !== faculties.length) {
  throw new Error("Duplicate faculty abbreviation detected");
}

console.log(`✓ Data valid: ${faculties.length} faculties, ${departments.length} departments`);

// ─── Helpers ──────────────────────────────────────────────────────────────────

const q = (s: string) => `"${s}"`;
const ind = (n: number) => " ".repeat(n);

// Build faculty → departments map
const facultyDeptMap = new Map<string, DepartmentEntry[]>();
for (const f of faculties) facultyDeptMap.set(f.name, []);
for (const d of departments) facultyDeptMap.get(d.faculty)!.push(d);

// ─── Generate ─────────────────────────────────────────────────────────────────

const lines: string[] = [];

lines.push(`// ─────────────────────────────────────────────────────────────────────────────`);
lines.push(`// AUTO-GENERATED — do not edit this file directly.`);
lines.push(`// Run \`npm run codegen\` from the repo root to regenerate from data/*.json`);
lines.push(`// ─────────────────────────────────────────────────────────────────────────────`);
lines.push(``);

// Faculties array
lines.push(`// ─── Faculties ───────────────────────────────────────────────────────────────`);
lines.push(``);
lines.push(`export const faculties = [`);
for (const f of faculties) lines.push(`${ind(2)}${q(f.name)},`);
lines.push(`] as const;`);
lines.push(``);
lines.push(`export type Faculty = (typeof faculties)[number];`);
lines.push(``);

// Departments array
lines.push(`// ─── Departments ─────────────────────────────────────────────────────────────`);
lines.push(``);
lines.push(`export const departments = [`);
for (const d of departments) lines.push(`${ind(2)}${q(d.name)},`);
lines.push(`] as const;`);
lines.push(``);
lines.push(`export type Department = (typeof departments)[number];`);
lines.push(``);

// facultyDepartments map
lines.push(`// ─── Faculty → Departments map ───────────────────────────────────────────────`);
lines.push(``);
lines.push(`export const facultyDepartments: Record<Faculty, readonly Department[]> = {`);
for (const f of faculties) {
  const depts = facultyDeptMap.get(f.name)!;
  lines.push(`${ind(2)}${q(f.name)}: [`);
  for (const d of depts) lines.push(`${ind(4)}${q(d.name)},`);
  lines.push(`${ind(2)}],`);
}
lines.push(`};`);
lines.push(``);

// Department abbreviations
lines.push(`// ─── Department abbreviations ────────────────────────────────────────────────`);
lines.push(``);
lines.push(`export const departmentAbbreviations: Record<Department, string> = {`);
for (const d of departments) lines.push(`${ind(2)}${q(d.name)}: ${q(d.abbreviation)},`);
lines.push(`};`);
lines.push(``);

// Faculty abbreviations
lines.push(`// ─── Faculty abbreviations ───────────────────────────────────────────────────`);
lines.push(``);
lines.push(`export const facultyAbbreviations: Record<Faculty, string> = {`);
for (const f of faculties) lines.push(`${ind(2)}${q(f.name)}: ${q(f.abbreviation)},`);
lines.push(`};`);
lines.push(``);

// Helper functions — copied verbatim, these never change
lines.push(`// ─── Abbreviation helpers ────────────────────────────────────────────────────`);
lines.push(``);
lines.push(`/** Returns the abbreviation for a department, or undefined if not found. */`);
lines.push(`export function getDepartmentAbbreviation(department: string): string | undefined {`);
lines.push(`  return departmentAbbreviations[department as Department];`);
lines.push(`}`);
lines.push(``);
lines.push(`/** Returns the abbreviation for a faculty, or undefined if not found. */`);
lines.push(`export function getFacultyAbbreviation(faculty: string): string | undefined {`);
lines.push(`  return facultyAbbreviations[faculty as Faculty];`);
lines.push(`}`);
lines.push(``);
lines.push(`/** Returns all departments with their abbreviations. Useful for dropdowns. */`);
lines.push(`export function listDepartmentsWithAbbreviations(): { name: Department; abbreviation: string }[] {`);
lines.push(`  return departments.map((name) => ({ name, abbreviation: departmentAbbreviations[name] }));`);
lines.push(`}`);
lines.push(``);
lines.push(`/** Returns all faculties with their abbreviations. Useful for dropdowns. */`);
lines.push(`export function listFacultiesWithAbbreviations(): { name: Faculty; abbreviation: string }[] {`);
lines.push(`  return faculties.map((name) => ({ name, abbreviation: facultyAbbreviations[name] }));`);
lines.push(`}`);
lines.push(``);
lines.push(`/** Finds a department by its abbreviation code (case-insensitive). */`);
lines.push(`export function getDepartmentByAbbreviation(abbreviation: string): Department | undefined {`);
lines.push(`  const upper = abbreviation.toUpperCase();`);
lines.push(`  return (Object.entries(departmentAbbreviations) as [Department, string][]).find(`);
lines.push(`    ([, code]) => code === upper`);
lines.push(`  )?.[0];`);
lines.push(`}`);
lines.push(``);
lines.push(`/** Finds a faculty by its abbreviation code (case-insensitive). */`);
lines.push(`export function getFacultyByAbbreviation(abbreviation: string): Faculty | undefined {`);
lines.push(`  const upper = abbreviation.toUpperCase();`);
lines.push(`  return (Object.entries(facultyAbbreviations) as [Faculty, string][]).find(`);
lines.push(`    ([, code]) => code === upper`);
lines.push(`  )?.[0];`);
lines.push(`}`);
lines.push(``);

// Formatter functions
lines.push(`// ─── Formatter functions ─────────────────────────────────────────────────────`);
lines.push(``);
lines.push(`/**`);
lines.push(` * Returns the official abbreviation for a department.`);
lines.push(` * Falls back to a generated abbreviation for unknown departments.`);
lines.push(` */`);
lines.push(`export function shortenDepartment(department: string): string {`);
lines.push(`  if (department in departmentAbbreviations) {`);
lines.push(`    return departmentAbbreviations[department as Department];`);
lines.push(`  }`);
lines.push(`  if (typeof department !== "string" || department.trim() === "") return "";`);
lines.push(`  const words = department.trim().split(/\\s+/);`);
lines.push(`  const mainWords = words.filter(`);
lines.push(`    (w) => w.toLowerCase() !== "of" && w.toLowerCase() !== "&"`);
lines.push(`  );`);
lines.push(`  const filtered = mainWords.length < 4`);
lines.push(`    ? words.filter((w) => w.toLowerCase() !== "&")`);
lines.push(`    : mainWords;`);
lines.push(`  if (filtered.length === 1) return filtered[0].charAt(0).toUpperCase();`);
lines.push(`  if (filtered.length === 2) {`);
lines.push(`    const [a, b] = filtered;`);
lines.push(`    return \`\${a.charAt(0)}\${a.length > 1 ? a.charAt(1) : ""}\${b.charAt(0)}\`.toUpperCase();`);
lines.push(`  }`);
lines.push(`  return filtered.map((w) => w.charAt(0).toUpperCase()).join(".");`);
lines.push(`}`);
lines.push(``);
lines.push(`/**`);
lines.push(` * Returns the official abbreviation for a faculty.`);
lines.push(` * Falls back to a generated abbreviation for unknown faculties.`);
lines.push(` */`);
lines.push(`export function shortenFaculty(faculty: string): string {`);
lines.push(`  if (faculty in facultyAbbreviations) {`);
lines.push(`    return facultyAbbreviations[faculty as Faculty];`);
lines.push(`  }`);
lines.push(`  const words = faculty.split(/\\s+/).filter(`);
lines.push(`    (w) => w.toLowerCase() !== "of" && w !== "&"`);
lines.push(`  );`);
lines.push(`  return words.map((w) => w.charAt(0).toUpperCase()).join("");`);
lines.push(`}`);
lines.push(``);
lines.push(`/**`);
lines.push(` * Formats a full name: first two names in full, third as initial, rest discarded.`);
lines.push(` * @example formatName("John Michael Doe Extra") // "John Michael D."`);
lines.push(` */`);
lines.push(`export function formatName(name: string): string {`);
lines.push(`  if (typeof name !== "string" || name.trim() === "") return "";`);
lines.push(`  const words = name.trim().split(/\\s+/);`);
lines.push(`  if (words.length === 1) return words[0];`);
lines.push(`  if (words.length === 2) return \`\${words[0]} \${words[1]}\`;`);
lines.push(`  return \`\${words[0]} \${words[1]} \${words[2].charAt(0).toUpperCase()}.\`;`);
lines.push(`}`);
lines.push(``);
lines.push(`/**`);
lines.push(` * Masks a registration number, keeping the first character and last 3 visible.`);
lines.push(` * @example maskRegNumber("F/HD/22/0012345") // "F***********345"`);
lines.push(` */`);
lines.push(`export function maskRegNumber(regNumber: string, mask = "*"): string {`);
lines.push(`  if (typeof regNumber !== "string" || regNumber.trim() === "") return "";`);
lines.push(`  const trimmed = regNumber.trim();`);
lines.push(`  const maskedLength = Math.max(0, trimmed.length - 4);`);
lines.push(`  return \`\${trimmed[0]}\${mask.repeat(maskedLength)}\${trimmed.slice(-3)}\`;`);
lines.push(`}`);
lines.push(``);

// Lookup helpers
lines.push(`// ─── Lookup helpers ──────────────────────────────────────────────────────────`);
lines.push(``);
lines.push(`/** Returns the departments for a given faculty. Falls back to all departments if not found. */`);
lines.push(`export function getDepartmentsByFaculty(faculty: string): readonly Department[] {`);
lines.push(`  return facultyDepartments[faculty as Faculty] ?? departments;`);
lines.push(`}`);
lines.push(``);
lines.push(`/** Returns the faculty a department belongs to, or undefined if not found. */`);
lines.push(`export function getFacultyByDepartment(department: string): Faculty | undefined {`);
lines.push(`  return (`);
lines.push(`    Object.entries(facultyDepartments) as [Faculty, readonly Department[]][]`);
lines.push(`  ).find(([, depts]) => depts.includes(department as Department))?.[0];`);
lines.push(`}`);
lines.push(``);
lines.push(`/** Returns true if the given string is a valid department name. */`);
lines.push(`export function isValidDepartment(value: string): value is Department {`);
lines.push(`  return (departments as readonly string[]).includes(value);`);
lines.push(`}`);
lines.push(``);
lines.push(`/** Returns true if the given string is a valid faculty name. */`);
lines.push(`export function isValidFaculty(value: string): value is Faculty {`);
lines.push(`  return (faculties as readonly string[]).includes(value);`);
lines.push(`}`);
lines.push(``);

const output = lines.join("\n");
const outPath = resolve(root, "packages/js/src/index.ts");
writeFileSync(outPath, output, "utf-8");

console.log(`✓ Generated ${outPath}`);
console.log(`  ${faculties.length} faculties · ${departments.length} departments`);