<?php
/**
 * scripts/codegen.php
 *
 * Reads data/faculties.json and data/departments.json and regenerates
 * packages/php/src/FutoDepartments.php
 *
 * Run from repo root: php scripts/codegen.php
 */

$root = dirname(__DIR__);
$dataDir = $root . '/data';
$outPath = $root . '/packages/php/src/FutoDepartments.php';

$faculties   = json_decode(file_get_contents($dataDir . '/faculties.json'), true);
$departments = json_decode(file_get_contents($dataDir . '/departments.json'), true);

// ── Validate ──────────────────────────────────────────────────────────────────

$facultyNames  = array_column($faculties, 'name');
$facultyAbbrevs = array_column($faculties, 'abbreviation');
$deptAbbrevs   = [];

foreach ($departments as $d) {
    if (!in_array($d['faculty'], $facultyNames, true)) {
        throw new RuntimeException("Department \"{$d['name']}\" references unknown faculty \"{$d['faculty']}\"");
    }
    if (in_array($d['abbreviation'], $deptAbbrevs, true)) {
        throw new RuntimeException("Duplicate department abbreviation \"{$d['abbreviation']}\" on \"{$d['name']}\"");
    }
    $deptAbbrevs[] = $d['abbreviation'];
}

if (count(array_unique($facultyAbbrevs)) !== count($facultyAbbrevs)) {
    throw new RuntimeException('Duplicate faculty abbreviation detected');
}

echo "✓ Data valid: " . count($faculties) . " faculties, " . count($departments) . " departments\n";

// ── Build faculty → departments map ──────────────────────────────────────────

$facultyDeptMap = [];
foreach ($faculties as $f) $facultyDeptMap[$f['name']] = [];
foreach ($departments as $d) $facultyDeptMap[$d['faculty']][] = $d;

// ── Helpers ───────────────────────────────────────────────────────────────────

function q(string $s): string { return "'" . addslashes($s) . "'"; }
function ind(int $n): string  { return str_repeat(' ', $n); }

function phpArray(array $items, int $indent): string {
    $lines = ["[\n"];
    foreach ($items as $item) {
        $lines[] = ind($indent + 4) . q($item) . ",\n";
    }
    $lines[] = ind($indent) . ']';
    return implode('', $lines);
}

// ── Generate FutoDepartments.php ─────────────────────────────────────────────

$lines = [];

$lines[] = "<?php\n";
$lines[] = "// ─────────────────────────────────────────────────────────────────────────────\n";
$lines[] = "// AUTO-GENERATED — do not edit this file directly.\n";
$lines[] = "// Run `php scripts/codegen.php` from the repo root to regenerate.\n";
$lines[] = "// ─────────────────────────────────────────────────────────────────────────────\n";
$lines[] = "\n";
$lines[] = "declare(strict_types=1);\n";
$lines[] = "\n";
$lines[] = "namespace Idikaeliada\\FutoDepartments;\n";
$lines[] = "\n";
$lines[] = "final class FutoDepartments\n";
$lines[] = "{\n";

// FACULTIES constant
$lines[] = "    // ─── Faculties ──────────────────────────────────────────────────────────\n\n";
$lines[] = "    public const FACULTIES = [\n";
foreach ($faculties as $f) {
    $lines[] = "        " . q($f['name']) . ",\n";
}
$lines[] = "    ];\n\n";

// DEPARTMENTS constant
$lines[] = "    // ─── Departments ─────────────────────────────────────────────────────────\n\n";
$lines[] = "    public const DEPARTMENTS = [\n";
foreach ($departments as $d) {
    $lines[] = "        " . q($d['name']) . ",\n";
}
$lines[] = "    ];\n\n";

// FACULTY_DEPARTMENTS constant
$lines[] = "    // ─── Faculty → Departments map ─────────────────────────────────────────\n\n";
$lines[] = "    public const FACULTY_DEPARTMENTS = [\n";
foreach ($faculties as $f) {
    $depts = $facultyDeptMap[$f['name']];
    $lines[] = "        " . q($f['name']) . " => [\n";
    foreach ($depts as $d) {
        $lines[] = "            " . q($d['name']) . ",\n";
    }
    $lines[] = "        ],\n";
}
$lines[] = "    ];\n\n";

// DEPARTMENT_ABBREVIATIONS constant
$lines[] = "    // ─── Department abbreviations ────────────────────────────────────────────\n\n";
$lines[] = "    public const DEPARTMENT_ABBREVIATIONS = [\n";
foreach ($departments as $d) {
    $lines[] = "        " . q($d['name']) . " => " . q($d['abbreviation']) . ",\n";
}
$lines[] = "    ];\n\n";

// FACULTY_ABBREVIATIONS constant
$lines[] = "    // ─── Faculty abbreviations ───────────────────────────────────────────────\n\n";
$lines[] = "    public const FACULTY_ABBREVIATIONS = [\n";
foreach ($faculties as $f) {
    $lines[] = "        " . q($f['name']) . " => " . q($f['abbreviation']) . ",\n";
}
$lines[] = "    ];\n\n";

// Helper methods
$lines[] = <<<'PHP'
    // ─── Abbreviation helpers ────────────────────────────────────────────────

    /** Returns the abbreviation for a department, or null if not found. */
    public static function getDepartmentAbbreviation(string $department): ?string
    {
        return self::DEPARTMENT_ABBREVIATIONS[$department] ?? null;
    }

    /** Returns the abbreviation for a faculty, or null if not found. */
    public static function getFacultyAbbreviation(string $faculty): ?string
    {
        return self::FACULTY_ABBREVIATIONS[$faculty] ?? null;
    }

    /** Returns all departments with their abbreviations. Useful for dropdowns. */
    public static function listDepartmentsWithAbbreviations(): array
    {
        return array_map(
            fn(string $name) => ['name' => $name, 'abbreviation' => self::DEPARTMENT_ABBREVIATIONS[$name]],
            self::DEPARTMENTS
        );
    }

    /** Returns all faculties with their abbreviations. Useful for dropdowns. */
    public static function listFacultiesWithAbbreviations(): array
    {
        return array_map(
            fn(string $name) => ['name' => $name, 'abbreviation' => self::FACULTY_ABBREVIATIONS[$name]],
            self::FACULTIES
        );
    }

    /** Finds a department by its abbreviation code (case-insensitive). */
    public static function getDepartmentByAbbreviation(string $abbreviation): ?string
    {
        $upper = strtoupper($abbreviation);
        $key = array_search($upper, self::DEPARTMENT_ABBREVIATIONS, true);
        return $key !== false ? $key : null;
    }

    /** Finds a faculty by its abbreviation code (case-insensitive). */
    public static function getFacultyByAbbreviation(string $abbreviation): ?string
    {
        $upper = strtoupper($abbreviation);
        $key = array_search($upper, self::FACULTY_ABBREVIATIONS, true);
        return $key !== false ? $key : null;
    }

    // ─── Formatter functions ─────────────────────────────────────────────────

    /**
     * Returns the official abbreviation for a department.
     * Falls back to a generated abbreviation for unknown departments.
     */
    public static function shortenDepartment(string $department): string
    {
        if (isset(self::DEPARTMENT_ABBREVIATIONS[$department])) {
            return self::DEPARTMENT_ABBREVIATIONS[$department];
        }
        $trimmed = trim($department);
        if ($trimmed === '') return '';
        $words = preg_split('/\s+/', $trimmed);
        $mainWords = array_values(array_filter($words, fn($w) => strtolower($w) !== 'of' && $w !== '&'));
        $filtered = count($mainWords) >= 4
            ? $mainWords
            : array_values(array_filter($words, fn($w) => $w !== '&'));
        if (count($filtered) === 1) return strtoupper(substr($filtered[0], 0, 1));
        if (count($filtered) === 2) {
            [$a, $b] = $filtered;
            return strtoupper($a[0] . (strlen($a) > 1 ? $a[1] : '') . $b[0]);
        }
        return implode('', array_map(fn($w) => strtoupper($w[0]), $filtered));
    }

    /**
     * Returns the official abbreviation for a faculty.
     * Falls back to a generated abbreviation for unknown faculties.
     */
    public static function shortenFaculty(string $faculty): string
    {
        if (isset(self::FACULTY_ABBREVIATIONS[$faculty])) {
            return self::FACULTY_ABBREVIATIONS[$faculty];
        }
        $words = preg_split('/\s+/', $faculty);
        $filtered = array_values(array_filter($words, fn($w) => strtolower($w) !== 'of' && $w !== '&'));
        return implode('', array_map(fn($w) => strtoupper($w[0]), $filtered));
    }

    /**
     * Formats a full name: first two names in full, third as initial, rest discarded.
     * @example FutoDepartments::formatName('John Michael Doe Extra') // 'John Michael D.'
     */
    public static function formatName(string $name): string
    {
        $trimmed = trim($name);
        if ($trimmed === '') return '';
        $words = preg_split('/\s+/', $trimmed);
        if (count($words) === 1) return $words[0];
        if (count($words) === 2) return "{$words[0]} {$words[1]}";
        return "{$words[0]} {$words[1]} " . strtoupper($words[2][0]) . '.';
    }

    /**
     * Masks a registration number, keeping the first character and last 3 visible.
     * @example FutoDepartments::maskRegNumber('F/HD/22/0012345') // 'F***********345'
     */
    public static function maskRegNumber(string $regNumber, string $mask = '*'): string
    {
        $trimmed = trim($regNumber);
        if ($trimmed === '') return '';
        $maskedLength = max(0, strlen($trimmed) - 4);
        return $trimmed[0] . str_repeat($mask, $maskedLength) . substr($trimmed, -3);
    }

    // ─── Lookup helpers ──────────────────────────────────────────────────────

    /** Returns the departments for a given faculty. Falls back to all departments if not found. */
    public static function getDepartmentsByFaculty(string $faculty): array
    {
        return self::FACULTY_DEPARTMENTS[$faculty] ?? self::DEPARTMENTS;
    }

    /** Returns the faculty a department belongs to, or null if not found. */
    public static function getFacultyByDepartment(string $department): ?string
    {
        foreach (self::FACULTY_DEPARTMENTS as $faculty => $depts) {
            if (in_array($department, $depts, true)) return $faculty;
        }
        return null;
    }

    /** Returns true if the given string is a valid department name. */
    public static function isValidDepartment(string $value): bool
    {
        return in_array($value, self::DEPARTMENTS, true);
    }

    /** Returns true if the given string is a valid faculty name. */
    public static function isValidFaculty(string $value): bool
    {
        return in_array($value, self::FACULTIES, true);
    }
}
PHP;

$lines[] = "\n";

file_put_contents($outPath, implode('', $lines));
echo "✓ Generated $outPath\n";
echo "  " . count($faculties) . " faculties · " . count($departments) . " departments\n";