#!/usr/bin/env python3
"""
scripts/codegen.py

Reads data/faculties.json and data/departments.json and regenerates
packages/python/futo_departments/__init__.py

Run from repo root: python scripts/codegen.py
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).parent.parent
data_dir = ROOT / "data"
out_path = ROOT / "packages" / "python" / "futo_departments" / "__init__.py"

faculties = json.loads((data_dir / "faculties.json").read_text())
departments = json.loads((data_dir / "departments.json").read_text())

# ── Validate ──────────────────────────────────────────────────────────────────

faculty_names = {f["name"] for f in faculties}
faculty_abbrevs = [f["abbreviation"] for f in faculties]
dept_abbrevs: list[str] = []

for d in departments:
    if d["faculty"] not in faculty_names:
        raise ValueError(f'Department "{d["name"]}" references unknown faculty "{d["faculty"]}"')
    if d["abbreviation"] in dept_abbrevs:
        raise ValueError(f'Duplicate department abbreviation "{d["abbreviation"]}" on "{d["name"]}"')
    dept_abbrevs.append(d["abbreviation"])

if len(set(faculty_abbrevs)) != len(faculty_abbrevs):
    raise ValueError("Duplicate faculty abbreviation detected")

print(f"✓ Data valid: {len(faculties)} faculties, {len(departments)} departments")

# ── Build faculty → departments map ──────────────────────────────────────────

faculty_dept_map: dict[str, list[dict]] = {f["name"]: [] for f in faculties}
for d in departments:
    faculty_dept_map[d["faculty"]].append(d)

# ── Helpers ───────────────────────────────────────────────────────────────────

def q(s: str) -> str:
    return f'"{s}"'

def indent(n: int) -> str:
    return " " * n

# ── Generate __init__.py ──────────────────────────────────────────────────────

lines: list[str] = []

lines += [
    "# ─────────────────────────────────────────────────────────────────────────────",
    "# AUTO-GENERATED — do not edit this file directly.",
    "# Run `python scripts/codegen.py` from the repo root to regenerate.",
    "# ─────────────────────────────────────────────────────────────────────────────",
    "",
    'from __future__ import annotations',
    "",
    "from typing import Literal, Optional",
    "",
]

# Faculty type
faculty_literal = ", ".join(f'"{f["name"]}"' for f in faculties)
lines += [
    "# ─── Types ───────────────────────────────────────────────────────────────────",
    "",
    f"Faculty = Literal[{faculty_literal}]",
    "",
]

dept_literal = ", ".join(f'"{d["name"]}"' for d in departments)
lines += [
    f"Department = Literal[{dept_literal}]",
    "",
]

# Faculties tuple
lines += [
    "# ─── Faculties ───────────────────────────────────────────────────────────────",
    "",
    "FACULTIES: tuple[str, ...] = (",
]
for f in faculties:
    lines.append(f'    {q(f["name"])},')
lines += [")", ""]

# Departments tuple
lines += [
    "# ─── Departments ─────────────────────────────────────────────────────────────",
    "",
    "DEPARTMENTS: tuple[str, ...] = (",
]
for d in departments:
    lines.append(f'    {q(d["name"])},')
lines += [")", ""]

# Faculty → departments map
lines += [
    "# ─── Faculty → Departments map ───────────────────────────────────────────────",
    "",
    "FACULTY_DEPARTMENTS: dict[str, tuple[str, ...]] = {",
]
for f in faculties:
    depts = faculty_dept_map[f["name"]]
    lines.append(f'    {q(f["name"])}: (')
    for d in depts:
        lines.append(f'        {q(d["name"])},')
    lines.append("    ),")
lines += ["}", ""]

# Department abbreviations
lines += [
    "# ─── Department abbreviations ────────────────────────────────────────────────",
    "",
    "DEPARTMENT_ABBREVIATIONS: dict[str, str] = {",
]
for d in departments:
    lines.append(f'    {q(d["name"])}: {q(d["abbreviation"])},')
lines += ["}", ""]

# Faculty abbreviations
lines += [
    "# ─── Faculty abbreviations ───────────────────────────────────────────────────",
    "",
    "FACULTY_ABBREVIATIONS: dict[str, str] = {",
]
for f in faculties:
    lines.append(f'    {q(f["name"])}: {q(f["abbreviation"])},')
lines += ["}", ""]

# Helper functions
lines += [
    "# ─── Abbreviation helpers ────────────────────────────────────────────────────",
    "",
    "def get_department_abbreviation(department: str) -> Optional[str]:",
    '    """Returns the abbreviation for a department, or None if not found."""',
    "    return DEPARTMENT_ABBREVIATIONS.get(department)",
    "",
    "def get_faculty_abbreviation(faculty: str) -> Optional[str]:",
    '    """Returns the abbreviation for a faculty, or None if not found."""',
    "    return FACULTY_ABBREVIATIONS.get(faculty)",
    "",
    "def list_departments_with_abbreviations() -> list[dict[str, str]]:",
    '    """Returns all departments and their abbreviations. Useful for dropdowns."""',
    "    return [",
    '        {"name": name, "abbreviation": DEPARTMENT_ABBREVIATIONS[name]}',
    "        for name in DEPARTMENTS",
    "    ]",
    "",
    "def list_faculties_with_abbreviations() -> list[dict[str, str]]:",
    '    """Returns all faculties and their abbreviations. Useful for dropdowns."""',
    "    return [",
    '        {"name": name, "abbreviation": FACULTY_ABBREVIATIONS[name]}',
    "        for name in FACULTIES",
    "    ]",
    "",
    "def get_department_by_abbreviation(abbreviation: str) -> Optional[str]:",
    '    """Finds a department by its abbreviation code (case-insensitive)."""',
    "    upper = abbreviation.upper()",
    "    return next(",
    "        (name for name, code in DEPARTMENT_ABBREVIATIONS.items() if code == upper),",
    "        None,",
    "    )",
    "",
    "def get_faculty_by_abbreviation(abbreviation: str) -> Optional[str]:",
    '    """Finds a faculty by its abbreviation code (case-insensitive)."""',
    "    upper = abbreviation.upper()",
    "    return next(",
    "        (name for name, code in FACULTY_ABBREVIATIONS.items() if code == upper),",
    "        None,",
    "    )",
    "",
    "",
    "# ─── Formatter functions ──────────────────────────────────────────────────────",
    "",
    "def shorten_department(department: str) -> str:",
    '    """',
    "    Returns the official abbreviation for a department.",
    "    Falls back to a generated abbreviation for unknown departments.",
    "",
    '    >>> shorten_department("Computer Science")',
    "    'CSC'",
    '    """',
    "    if department in DEPARTMENT_ABBREVIATIONS:",
    "        return DEPARTMENT_ABBREVIATIONS[department]",
    "    if not department or not department.strip():",
    '        return ""',
    "    words = department.strip().split()",
    "    main_words = [w for w in words if w.lower() not in ('of', '&')]",
    "    filtered = main_words if len(main_words) >= 4 else [w for w in words if w.lower() != '&']",
    "    if len(filtered) == 1:",
    "        return filtered[0][0].upper()",
    "    if len(filtered) == 2:",
    "        a, b = filtered",
    "        return (a[0] + (a[1] if len(a) > 1 else '') + b[0]).upper()",
    "    return ''.join(w[0].upper() for w in filtered)",
    "",
    "",
    "def shorten_faculty(faculty: str) -> str:",
    '    """',
    "    Returns the official abbreviation for a faculty.",
    "    Falls back to a generated abbreviation for unknown faculties.",
    "",
    '    >>> shorten_faculty("College of Medicine")',
    "    'COM'",
    '    """',
    "    if faculty in FACULTY_ABBREVIATIONS:",
    "        return FACULTY_ABBREVIATIONS[faculty]",
    "    words = [w for w in faculty.split() if w.lower() not in ('of', '&')]",
    "    return ''.join(w[0].upper() for w in words)",
    "",
    "",
    "def format_name(name: str) -> str:",
    '    """',
    "    Formats a full name: first two names in full, third as initial, rest discarded.",
    "",
    '    >>> format_name("John Michael Doe Extra")',
    "    'John Michael D.'",
    '    """',
    "    if not name or not name.strip():",
    '        return ""',
    "    words = name.strip().split()",
    "    if len(words) == 1:",
    "        return words[0]",
    "    if len(words) == 2:",
    "        return f'{words[0]} {words[1]}'",
    "    return f'{words[0]} {words[1]} {words[2][0].upper()}.'",
    "",
    "",
    "def mask_reg_number(reg_number: str, mask: str = '*') -> str:",
    '    """',
    "    Masks a registration number, keeping the first character and last 3 visible.",
    "",
    '    >>> mask_reg_number("F/HD/22/0012345")',
    "    'F***********345'",
    '    """',
    "    if not reg_number or not reg_number.strip():",
    '        return ""',
    "    trimmed = reg_number.strip()",
    "    masked_length = max(0, len(trimmed) - 4)",
    "    return f'{trimmed[0]}{mask * masked_length}{trimmed[-3:]}'",
    "",
    "",
    "# ─── Lookup helpers ──────────────────────────────────────────────────────────",
    "",
    "def get_departments_by_faculty(faculty: str) -> tuple[str, ...]:",
    '    """',
    "    Returns the departments for a given faculty.",
    "    Falls back to all departments if the faculty is not found.",
    '    """',
    "    return FACULTY_DEPARTMENTS.get(faculty, DEPARTMENTS)",
    "",
    "",
    "def get_faculty_by_department(department: str) -> Optional[str]:",
    '    """Returns the faculty a department belongs to, or None if not found."""',
    "    return next(",
    "        (faculty for faculty, depts in FACULTY_DEPARTMENTS.items() if department in depts),",
    "        None,",
    "    )",
    "",
    "",
    "def is_valid_department(value: str) -> bool:",
    '    """Returns True if the given string is a valid department name."""',
    "    return value in DEPARTMENTS",
    "",
    "",
    "def is_valid_faculty(value: str) -> bool:",
    '    """Returns True if the given string is a valid faculty name."""',
    "    return value in FACULTIES",
    "",
    "",
    "# ─── Public API ──────────────────────────────────────────────────────────────",
    "",
    "__all__ = [",
    '    "Faculty",',
    '    "Department",',
    '    "FACULTIES",',
    '    "DEPARTMENTS",',
    '    "FACULTY_DEPARTMENTS",',
    '    "DEPARTMENT_ABBREVIATIONS",',
    '    "FACULTY_ABBREVIATIONS",',
    '    "get_department_abbreviation",',
    '    "get_faculty_abbreviation",',
    '    "list_departments_with_abbreviations",',
    '    "list_faculties_with_abbreviations",',
    '    "get_department_by_abbreviation",',
    '    "get_faculty_by_abbreviation",',
    '    "shorten_department",',
    '    "shorten_faculty",',
    '    "format_name",',
    '    "mask_reg_number",',
    '    "get_departments_by_faculty",',
    '    "get_faculty_by_department",',
    '    "is_valid_department",',
    '    "is_valid_faculty",',
    "]",
    "",
]

out_path.parent.mkdir(parents=True, exist_ok=True)
out_path.write_text("\n".join(lines))

print(f"✓ Generated {out_path}")
print(f"  {len(faculties)} faculties · {len(departments)} departments")