#!/usr/bin/env python3
"""
scripts/codegen_java.py

Reads data/faculties.json and data/departments.json and regenerates
packages/java/src/main/java/com/idikaeliada/futo/FutoDepartments.java

Run from repo root: python scripts/codegen_java.py
"""

import json
from pathlib import Path

ROOT = Path(__file__).parent.parent
data_dir = ROOT / "data"
out_path = ROOT / "packages" / "java" / "src" / "main" / "java" / "com" / "idikaeliada" / "futo" / "FutoDepartments.java"

faculties   = json.loads((data_dir / "faculties.json").read_text(encoding="utf-8"))
departments = json.loads((data_dir / "departments.json").read_text(encoding="utf-8"))

# ── Validate ──────────────────────────────────────────────────────────────────

faculty_names  = {f["name"] for f in faculties}
faculty_abbrevs = [f["abbreviation"] for f in faculties]
dept_abbrevs: list[str] = []

for d in departments:
    if d["faculty"] not in faculty_names:
        raise ValueError(f'Department "{d["name"]}" references unknown faculty "{d["faculty"]}"')
    if d["abbreviation"] in dept_abbrevs:
        raise ValueError(f'Duplicate department abbreviation "{d["abbreviation"]}" on "{d["name"]}"')
    dept_abbrevs.append(d["abbreviation"])

if len(set(faculty_abbrevs)) != len(faculty_abbrevs):
    raise ValueError("Duplicate faculty abbreviation detected")

print(f"✓ Data valid: {len(faculties)} faculties, {len(departments)} departments")

# ── Build faculty → departments map ──────────────────────────────────────────

faculty_dept_map: dict[str, list[dict]] = {f["name"]: [] for f in faculties}
for d in departments:
    faculty_dept_map[d["faculty"]].append(d)

def jstr(s: str) -> str:
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

# ── Generate FutoDepartments.java ─────────────────────────────────────────────

lines: list[str] = []

lines += [
    "// ─────────────────────────────────────────────────────────────────────────────",
    "// AUTO-GENERATED — do not edit this file directly.",
    "// Run `python scripts/codegen_java.py` from the repo root to regenerate.",
    "// ─────────────────────────────────────────────────────────────────────────────",
    "",
    "package com.idikaeliada.futo;",
    "",
    "import java.util.*;",
    "",
    "/**",
    " * FUTO (Federal University of Technology Owerri) faculties and departments data.",
    " * All methods are static — no instantiation needed.",
    " */",
    "public final class FutoDepartments {",
    "",
    "    private FutoDepartments() {}",
    "",
]

# FACULTIES list
lines += [
    "    // ─── Faculties ────────────────────────────────────────────────────────────",
    "",
    "    public static final List<String> FACULTIES = Collections.unmodifiableList(Arrays.asList(",
]
for i, f in enumerate(faculties):
    comma = "" if i == len(faculties) - 1 else ","
    lines.append(f"        {jstr(f['name'])}{comma}")
lines += ["    ));", ""]

# DEPARTMENTS list
lines += [
    "    // ─── Departments ──────────────────────────────────────────────────────────",
    "",
    "    public static final List<String> DEPARTMENTS = Collections.unmodifiableList(Arrays.asList(",
]
for i, d in enumerate(departments):
    comma = "" if i == len(departments) - 1 else ","
    lines.append(f"        {jstr(d['name'])}{comma}")
lines += ["    ));", ""]

# FACULTY_DEPARTMENTS map
lines += [
    "    // ─── Faculty → Departments map ────────────────────────────────────────────",
    "",
    "    public static final Map<String, List<String>> FACULTY_DEPARTMENTS;",
    "    static {",
    "        Map<String, List<String>> map = new LinkedHashMap<>();",
]
for f in faculties:
    depts = faculty_dept_map[f["name"]]
    dept_strs = ", ".join(jstr(d["name"]) for d in depts)
    lines.append(f"        map.put({jstr(f['name'])}, Collections.unmodifiableList(Arrays.asList({dept_strs})));")
lines += [
    "        FACULTY_DEPARTMENTS = Collections.unmodifiableMap(map);",
    "    }",
    "",
]

# DEPARTMENT_ABBREVIATIONS map
lines += [
    "    // ─── Department abbreviations ─────────────────────────────────────────────",
    "",
    "    public static final Map<String, String> DEPARTMENT_ABBREVIATIONS;",
    "    static {",
    "        Map<String, String> map = new LinkedHashMap<>();",
]
for d in departments:
    lines.append(f"        map.put({jstr(d['name'])}, {jstr(d['abbreviation'])});")
lines += [
    "        DEPARTMENT_ABBREVIATIONS = Collections.unmodifiableMap(map);",
    "    }",
    "",
]

# FACULTY_ABBREVIATIONS map
lines += [
    "    // ─── Faculty abbreviations ────────────────────────────────────────────────",
    "",
    "    public static final Map<String, String> FACULTY_ABBREVIATIONS;",
    "    static {",
    "        Map<String, String> map = new LinkedHashMap<>();",
]
for f in faculties:
    lines.append(f"        map.put({jstr(f['name'])}, {jstr(f['abbreviation'])});")
lines += [
    "        FACULTY_ABBREVIATIONS = Collections.unmodifiableMap(map);",
    "    }",
    "",
]

# Helper methods
lines += [
    "    // ─── Abbreviation helpers ─────────────────────────────────────────────────",
    "",
    "    /** Returns the abbreviation for a department, or null if not found. */",
    "    public static String getDepartmentAbbreviation(String department) {",
    "        return DEPARTMENT_ABBREVIATIONS.get(department);",
    "    }",
    "",
    "    /** Returns the abbreviation for a faculty, or null if not found. */",
    "    public static String getFacultyAbbreviation(String faculty) {",
    "        return FACULTY_ABBREVIATIONS.get(faculty);",
    "    }",
    "",
    "    /** Returns all departments with their abbreviations. Useful for dropdowns. */",
    "    public static List<Map<String, String>> listDepartmentsWithAbbreviations() {",
    "        List<Map<String, String>> result = new ArrayList<>();",
    "        for (String name : DEPARTMENTS) {",
    "            Map<String, String> entry = new LinkedHashMap<>();",
    "            entry.put(\"name\", name);",
    "            entry.put(\"abbreviation\", DEPARTMENT_ABBREVIATIONS.get(name));",
    "            result.add(Collections.unmodifiableMap(entry));",
    "        }",
    "        return Collections.unmodifiableList(result);",
    "    }",
    "",
    "    /** Returns all faculties with their abbreviations. Useful for dropdowns. */",
    "    public static List<Map<String, String>> listFacultiesWithAbbreviations() {",
    "        List<Map<String, String>> result = new ArrayList<>();",
    "        for (String name : FACULTIES) {",
    "            Map<String, String> entry = new LinkedHashMap<>();",
    "            entry.put(\"name\", name);",
    "            entry.put(\"abbreviation\", FACULTY_ABBREVIATIONS.get(name));",
    "            result.add(Collections.unmodifiableMap(entry));",
    "        }",
    "        return Collections.unmodifiableList(result);",
    "    }",
    "",
    "    /** Finds a department by its abbreviation code (case-insensitive). */",
    "    public static String getDepartmentByAbbreviation(String abbreviation) {",
    "        if (abbreviation == null) return null;",
    "        String upper = abbreviation.toUpperCase();",
    "        for (Map.Entry<String, String> entry : DEPARTMENT_ABBREVIATIONS.entrySet()) {",
    "            if (entry.getValue().equals(upper)) return entry.getKey();",
    "        }",
    "        return null;",
    "    }",
    "",
    "    /** Finds a faculty by its abbreviation code (case-insensitive). */",
    "    public static String getFacultyByAbbreviation(String abbreviation) {",
    "        if (abbreviation == null) return null;",
    "        String upper = abbreviation.toUpperCase();",
    "        for (Map.Entry<String, String> entry : FACULTY_ABBREVIATIONS.entrySet()) {",
    "            if (entry.getValue().equals(upper)) return entry.getKey();",
    "        }",
    "        return null;",
    "    }",
    "",
    "    // ─── Formatter functions ──────────────────────────────────────────────────",
    "",
    "    /**",
    "     * Returns the official abbreviation for a department.",
    "     * Falls back to a generated abbreviation for unknown departments.",
    "     */",
    "    public static String shortenDepartment(String department) {",
    "        if (department == null) return \"\";",
    "        if (DEPARTMENT_ABBREVIATIONS.containsKey(department)) {",
    "            return DEPARTMENT_ABBREVIATIONS.get(department);",
    "        }",
    "        String trimmed = department.trim();",
    "        if (trimmed.isEmpty()) return \"\";",
    "        String[] words = trimmed.split(\"\\\\s+\");",
    "        List<String> mainWords = new ArrayList<>();",
    "        for (String w : words) {",
    "            if (!w.equalsIgnoreCase(\"of\") && !w.equals(\"&\")) mainWords.add(w);",
    "        }",
    "        List<String> filtered;",
    "        if (mainWords.size() >= 4) {",
    "            filtered = mainWords;",
    "        } else {",
    "            filtered = new ArrayList<>();",
    "            for (String w : words) { if (!w.equals(\"&\")) filtered.add(w); }",
    "        }",
    "        if (filtered.isEmpty()) return \"\";",
    "        if (filtered.size() == 1) return filtered.get(0).substring(0, 1).toUpperCase();",
    "        if (filtered.size() == 2) {",
    "            String a = filtered.get(0), b = filtered.get(1);",
    "            return (a.charAt(0) + (a.length() > 1 ? String.valueOf(a.charAt(1)) : \"\") + b.charAt(0)).toUpperCase();",
    "        }",
    "        StringBuilder sb = new StringBuilder();",
    "        for (String w : filtered) sb.append(Character.toUpperCase(w.charAt(0)));",
    "        return sb.toString();",
    "    }",
    "",
    "    /**",
    "     * Returns the official abbreviation for a faculty.",
    "     * Falls back to a generated abbreviation for unknown faculties.",
    "     */",
    "    public static String shortenFaculty(String faculty) {",
    "        if (faculty == null) return \"\";",
    "        if (FACULTY_ABBREVIATIONS.containsKey(faculty)) {",
    "            return FACULTY_ABBREVIATIONS.get(faculty);",
    "        }",
    "        String[] words = faculty.split(\"\\\\s+\");",
    "        StringBuilder sb = new StringBuilder();",
    "        for (String w : words) {",
    "            if (!w.equalsIgnoreCase(\"of\") && !w.equals(\"&\")) {",
    "                sb.append(Character.toUpperCase(w.charAt(0)));",
    "            }",
    "        }",
    "        return sb.toString();",
    "    }",
    "",
    "    /**",
    "     * Formats a full name: first two names in full, third as initial, rest discarded.",
    "     * Example: formatName(\"John Michael Doe Extra\") returns \"John Michael D.\"",
    "     */",
    "    public static String formatName(String name) {",
    "        if (name == null) return \"\";",
    "        String trimmed = name.trim();",
    "        if (trimmed.isEmpty()) return \"\";",
    "        String[] words = trimmed.split(\"\\\\s+\");",
    "        if (words.length == 1) return words[0];",
    "        if (words.length == 2) return words[0] + \" \" + words[1];",
    "        return words[0] + \" \" + words[1] + \" \" + Character.toUpperCase(words[2].charAt(0)) + \".\";",
    "    }",
    "",
    "    /**",
    "     * Masks a registration number, keeping the first character and last 3 visible.",
    "     * Example: maskRegNumber(\"F/HD/22/0012345\") returns \"F***********345\"",
    "     */",
    "    public static String maskRegNumber(String regNumber) {",
    "        return maskRegNumber(regNumber, '*');",
    "    }",
    "",
    "    public static String maskRegNumber(String regNumber, char mask) {",
    "        if (regNumber == null) return \"\";",
    "        String trimmed = regNumber.trim();",
    "        if (trimmed.isEmpty()) return \"\";",
    "        int maskedLength = Math.max(0, trimmed.length() - 4);",
    "        return trimmed.charAt(0)",
    "            + String.valueOf(mask).repeat(maskedLength)",
    "            + trimmed.substring(trimmed.length() - 3);",
    "    }",
    "",
    "    // ─── Lookup helpers ───────────────────────────────────────────────────────",
    "",
    "    /** Returns the departments for a given faculty. Falls back to all departments if not found. */",
    "    public static List<String> getDepartmentsByFaculty(String faculty) {",
    "        return FACULTY_DEPARTMENTS.getOrDefault(faculty, DEPARTMENTS);",
    "    }",
    "",
    "    /** Returns the faculty a department belongs to, or null if not found. */",
    "    public static String getFacultyByDepartment(String department) {",
    "        for (Map.Entry<String, List<String>> entry : FACULTY_DEPARTMENTS.entrySet()) {",
    "            if (entry.getValue().contains(department)) return entry.getKey();",
    "        }",
    "        return null;",
    "    }",
    "",
    "    /** Returns true if the given string is a valid department name. */",
    "    public static boolean isValidDepartment(String value) {",
    "        return DEPARTMENTS.contains(value);",
    "    }",
    "",
    "    /** Returns true if the given string is a valid faculty name. */",
    "    public static boolean isValidFaculty(String value) {",
    "        return FACULTIES.contains(value);",
    "    }",
    "}",
]

out_path.parent.mkdir(parents=True, exist_ok=True)
out_path.write_text("\n".join(lines), encoding="utf-8")

print(f"✓ Generated {out_path}")
print(f"  {len(faculties)} faculties · {len(departments)} departments")