# ─────────────────────────────────────────────────────────────────────────────
# AUTO-GENERATED — do not edit this file directly.
# Run `python scripts/codegen.py` from the repo root to regenerate.
# ─────────────────────────────────────────────────────────────────────────────

from __future__ import annotations

from typing import Literal, Optional

# ─── Types ───────────────────────────────────────────────────────────────────

Faculty = Literal["School of Engineering & Engineering Technology", "School of Physical Sciences", "School of Biological Sciences", "School of Agriculture & Agricultural Technology", "School of Information & Communication Technology", "School of Environmental Sciences", "School of Logistics & Innovation Technology", "School of Health Technology", "School of Electrical Systems & Engineering Technology", "School of Basic Medical Sciences", "College of Medicine", "Ce-Sustainable Procurement, Environmental & Social Standards"]

Department = Literal["Petroleum Engineering", "Materials & Metallurgical Engineering", "Mechanical Engineering", "Civil Engineering", "Chemical Engineering", "Food Science & Technology", "Polymer & Textile Engineering", "Biomedical Engineering", "Agricultural and Bioresources Engineering", "Mathematics", "Physics", "Chemistry", "Statistics", "Science Laboratory Technology", "Biochemistry", "Microbiology", "Biotechnology", "Biology", "Forensic Science", "Crop Science and Technology", "Agricultural Economics", "Agricultural Extension", "Animal Science and Technology", "Fisheries and Aquaculture Technology", "Forestry and Wildlife Technology", "Soil Science and Technology", "Computer Science", "Software Engineering", "Cyber Security", "Information Technology", "Architecture", "Building Technology", "Environmental Management", "Quantity Surveying", "Surveying and Geoinformatics", "Urban and Regional Planning", "Estate Management and Evaluation", "Logistics & Transport Technology", "Entrepreneurship & Innovation", "Maritime Technology and Logistics", "Supply Chain Management", "Financial Innovation and Technology", "Project Management Technology", "Prosthetics and Orthotics", "Environmental Health Science", "Optometry", "Public Health Technology", "Dental Technology", "Radiography", "Mechatronics Engineering", "Computer Engineering", "Electronics Engineering", "Telecommunications Engineering", "Electrical (Power Systems) Engineering", "Human Anatomy", "Human Physiology", "Medicine and Surgery (MBBS)", "Sustainable Social Development", "Sustainable Environmental Studies", "Procurement Management"]

# ─── Faculties ───────────────────────────────────────────────────────────────

FACULTIES: tuple[str, ...] = (
    "School of Engineering & Engineering Technology",
    "School of Physical Sciences",
    "School of Biological Sciences",
    "School of Agriculture & Agricultural Technology",
    "School of Information & Communication Technology",
    "School of Environmental Sciences",
    "School of Logistics & Innovation Technology",
    "School of Health Technology",
    "School of Electrical Systems & Engineering Technology",
    "School of Basic Medical Sciences",
    "College of Medicine",
    "Ce-Sustainable Procurement, Environmental & Social Standards",
)

# ─── Departments ─────────────────────────────────────────────────────────────

DEPARTMENTS: tuple[str, ...] = (
    "Petroleum Engineering",
    "Materials & Metallurgical Engineering",
    "Mechanical Engineering",
    "Civil Engineering",
    "Chemical Engineering",
    "Food Science & Technology",
    "Polymer & Textile Engineering",
    "Biomedical Engineering",
    "Agricultural and Bioresources Engineering",
    "Mathematics",
    "Physics",
    "Chemistry",
    "Statistics",
    "Science Laboratory Technology",
    "Biochemistry",
    "Microbiology",
    "Biotechnology",
    "Biology",
    "Forensic Science",
    "Crop Science and Technology",
    "Agricultural Economics",
    "Agricultural Extension",
    "Animal Science and Technology",
    "Fisheries and Aquaculture Technology",
    "Forestry and Wildlife Technology",
    "Soil Science and Technology",
    "Computer Science",
    "Software Engineering",
    "Cyber Security",
    "Information Technology",
    "Architecture",
    "Building Technology",
    "Environmental Management",
    "Quantity Surveying",
    "Surveying and Geoinformatics",
    "Urban and Regional Planning",
    "Estate Management and Evaluation",
    "Logistics & Transport Technology",
    "Entrepreneurship & Innovation",
    "Maritime Technology and Logistics",
    "Supply Chain Management",
    "Financial Innovation and Technology",
    "Project Management Technology",
    "Prosthetics and Orthotics",
    "Environmental Health Science",
    "Optometry",
    "Public Health Technology",
    "Dental Technology",
    "Radiography",
    "Mechatronics Engineering",
    "Computer Engineering",
    "Electronics Engineering",
    "Telecommunications Engineering",
    "Electrical (Power Systems) Engineering",
    "Human Anatomy",
    "Human Physiology",
    "Medicine and Surgery (MBBS)",
    "Sustainable Social Development",
    "Sustainable Environmental Studies",
    "Procurement Management",
)

# ─── Faculty → Departments map ───────────────────────────────────────────────

FACULTY_DEPARTMENTS: dict[str, tuple[str, ...]] = {
    "School of Engineering & Engineering Technology": (
        "Petroleum Engineering",
        "Materials & Metallurgical Engineering",
        "Mechanical Engineering",
        "Civil Engineering",
        "Chemical Engineering",
        "Food Science & Technology",
        "Polymer & Textile Engineering",
        "Biomedical Engineering",
        "Agricultural and Bioresources Engineering",
    ),
    "School of Physical Sciences": (
        "Mathematics",
        "Physics",
        "Chemistry",
        "Statistics",
        "Science Laboratory Technology",
    ),
    "School of Biological Sciences": (
        "Biochemistry",
        "Microbiology",
        "Biotechnology",
        "Biology",
        "Forensic Science",
    ),
    "School of Agriculture & Agricultural Technology": (
        "Crop Science and Technology",
        "Agricultural Economics",
        "Agricultural Extension",
        "Animal Science and Technology",
        "Fisheries and Aquaculture Technology",
        "Forestry and Wildlife Technology",
        "Soil Science and Technology",
    ),
    "School of Information & Communication Technology": (
        "Computer Science",
        "Software Engineering",
        "Cyber Security",
        "Information Technology",
    ),
    "School of Environmental Sciences": (
        "Architecture",
        "Building Technology",
        "Environmental Management",
        "Quantity Surveying",
        "Surveying and Geoinformatics",
        "Urban and Regional Planning",
        "Estate Management and Evaluation",
    ),
    "School of Logistics & Innovation Technology": (
        "Logistics & Transport Technology",
        "Entrepreneurship & Innovation",
        "Maritime Technology and Logistics",
        "Supply Chain Management",
        "Financial Innovation and Technology",
        "Project Management Technology",
    ),
    "School of Health Technology": (
        "Prosthetics and Orthotics",
        "Environmental Health Science",
        "Optometry",
        "Public Health Technology",
        "Dental Technology",
        "Radiography",
    ),
    "School of Electrical Systems & Engineering Technology": (
        "Mechatronics Engineering",
        "Computer Engineering",
        "Electronics Engineering",
        "Telecommunications Engineering",
        "Electrical (Power Systems) Engineering",
    ),
    "School of Basic Medical Sciences": (
        "Human Anatomy",
        "Human Physiology",
    ),
    "College of Medicine": (
        "Medicine and Surgery (MBBS)",
    ),
    "Ce-Sustainable Procurement, Environmental & Social Standards": (
        "Sustainable Social Development",
        "Sustainable Environmental Studies",
        "Procurement Management",
    ),
}

# ─── Department abbreviations ────────────────────────────────────────────────

DEPARTMENT_ABBREVIATIONS: dict[str, str] = {
    "Petroleum Engineering": "PET",
    "Materials & Metallurgical Engineering": "MME",
    "Mechanical Engineering": "MEE",
    "Civil Engineering": "CIE",
    "Chemical Engineering": "CHE",
    "Food Science & Technology": "FST",
    "Polymer & Textile Engineering": "PTE",
    "Biomedical Engineering": "BME",
    "Agricultural and Bioresources Engineering": "ABE",
    "Mathematics": "MTH",
    "Physics": "PHY",
    "Chemistry": "CHM",
    "Statistics": "STA",
    "Science Laboratory Technology": "SLT",
    "Biochemistry": "BCH",
    "Microbiology": "MCB",
    "Biotechnology": "BTC",
    "Biology": "BIO",
    "Forensic Science": "FRS",
    "Crop Science and Technology": "CST",
    "Agricultural Economics": "AEC",
    "Agricultural Extension": "AEX",
    "Animal Science and Technology": "AST",
    "Fisheries and Aquaculture Technology": "FAT",
    "Forestry and Wildlife Technology": "FWT",
    "Soil Science and Technology": "SST",
    "Computer Science": "CSC",
    "Software Engineering": "SOE",
    "Cyber Security": "CYB",
    "Information Technology": "IFT",
    "Architecture": "ARC",
    "Building Technology": "BLD",
    "Environmental Management": "EVM",
    "Quantity Surveying": "QST",
    "Surveying and Geoinformatics": "SVG",
    "Urban and Regional Planning": "URP",
    "Estate Management and Evaluation": "ESV",
    "Logistics & Transport Technology": "LTT",
    "Entrepreneurship & Innovation": "ENI",
    "Maritime Technology and Logistics": "MST",
    "Supply Chain Management": "SCM",
    "Financial Innovation and Technology": "FIT",
    "Project Management Technology": "PMT",
    "Prosthetics and Orthotics": "POT",
    "Environmental Health Science": "EHS",
    "Optometry": "OPT",
    "Public Health Technology": "PUH",
    "Dental Technology": "DNT",
    "Radiography": "RAD",
    "Mechatronics Engineering": "MCE",
    "Computer Engineering": "CPE",
    "Electronics Engineering": "ELE",
    "Telecommunications Engineering": "TCE",
    "Electrical (Power Systems) Engineering": "EPE",
    "Human Anatomy": "ANA",
    "Human Physiology": "PHS",
    "Medicine and Surgery (MBBS)": "MBBS",
    "Sustainable Social Development": "SSD",
    "Sustainable Environmental Studies": "SES",
    "Procurement Management": "PRM",
}

# ─── Faculty abbreviations ───────────────────────────────────────────────────

FACULTY_ABBREVIATIONS: dict[str, str] = {
    "School of Engineering & Engineering Technology": "SEET",
    "School of Physical Sciences": "SOPS",
    "School of Biological Sciences": "SOBS",
    "School of Agriculture & Agricultural Technology": "SAAT",
    "School of Information & Communication Technology": "SICT",
    "School of Environmental Sciences": "SOES",
    "School of Logistics & Innovation Technology": "SLIT",
    "School of Health Technology": "SOHT",
    "School of Electrical Systems & Engineering Technology": "SESET",
    "School of Basic Medical Sciences": "SBMS",
    "College of Medicine": "COM",
    "Ce-Sustainable Procurement, Environmental & Social Standards": "CESPESS",
}

# ─── Abbreviation helpers ────────────────────────────────────────────────────

def get_department_abbreviation(department: str) -> Optional[str]:
    """Returns the abbreviation for a department, or None if not found."""
    return DEPARTMENT_ABBREVIATIONS.get(department)

def get_faculty_abbreviation(faculty: str) -> Optional[str]:
    """Returns the abbreviation for a faculty, or None if not found."""
    return FACULTY_ABBREVIATIONS.get(faculty)

def list_departments_with_abbreviations() -> list[dict[str, str]]:
    """Returns all departments and their abbreviations. Useful for dropdowns."""
    return [
        {"name": name, "abbreviation": DEPARTMENT_ABBREVIATIONS[name]}
        for name in DEPARTMENTS
    ]

def list_faculties_with_abbreviations() -> list[dict[str, str]]:
    """Returns all faculties and their abbreviations. Useful for dropdowns."""
    return [
        {"name": name, "abbreviation": FACULTY_ABBREVIATIONS[name]}
        for name in FACULTIES
    ]

def get_department_by_abbreviation(abbreviation: str) -> Optional[str]:
    """Finds a department by its abbreviation code (case-insensitive)."""
    upper = abbreviation.upper()
    return next(
        (name for name, code in DEPARTMENT_ABBREVIATIONS.items() if code == upper),
        None,
    )

def get_faculty_by_abbreviation(abbreviation: str) -> Optional[str]:
    """Finds a faculty by its abbreviation code (case-insensitive)."""
    upper = abbreviation.upper()
    return next(
        (name for name, code in FACULTY_ABBREVIATIONS.items() if code == upper),
        None,
    )


# ─── Formatter functions ──────────────────────────────────────────────────────

def shorten_department(department: str) -> str:
    """
    Returns the official abbreviation for a department.
    Falls back to a generated abbreviation for unknown departments.

    >>> shorten_department("Computer Science")
    'CSC'
    """
    if department in DEPARTMENT_ABBREVIATIONS:
        return DEPARTMENT_ABBREVIATIONS[department]
    if not department or not department.strip():
        return ""
    words = department.strip().split()
    main_words = [w for w in words if w.lower() not in ('of', '&')]
    filtered = main_words if len(main_words) >= 4 else [w for w in words if w.lower() != '&']
    if len(filtered) == 1:
        return filtered[0][0].upper()
    if len(filtered) == 2:
        a, b = filtered
        return (a[0] + (a[1] if len(a) > 1 else '') + b[0]).upper()
    return ''.join(w[0].upper() for w in filtered)


def shorten_faculty(faculty: str) -> str:
    """
    Returns the official abbreviation for a faculty.
    Falls back to a generated abbreviation for unknown faculties.

    >>> shorten_faculty("College of Medicine")
    'COM'
    """
    if faculty in FACULTY_ABBREVIATIONS:
        return FACULTY_ABBREVIATIONS[faculty]
    words = [w for w in faculty.split() if w.lower() not in ('of', '&')]
    return ''.join(w[0].upper() for w in words)


def format_name(name: str) -> str:
    """
    Formats a full name: first two names in full, third as initial, rest discarded.

    >>> format_name("John Michael Doe Extra")
    'John Michael D.'
    """
    if not name or not name.strip():
        return ""
    words = name.strip().split()
    if len(words) == 1:
        return words[0]
    if len(words) == 2:
        return f'{words[0]} {words[1]}'
    return f'{words[0]} {words[1]} {words[2][0].upper()}.'


def mask_reg_number(reg_number: str, mask: str = '*') -> str:
    """
    Masks a registration number, keeping the first character and last 3 visible.

    >>> mask_reg_number("F/HD/22/0012345")
    'F***********345'
    """
    if not reg_number or not reg_number.strip():
        return ""
    trimmed = reg_number.strip()
    masked_length = max(0, len(trimmed) - 4)
    return f'{trimmed[0]}{mask * masked_length}{trimmed[-3:]}'


# ─── Lookup helpers ──────────────────────────────────────────────────────────

def get_departments_by_faculty(faculty: str) -> tuple[str, ...]:
    """
    Returns the departments for a given faculty.
    Falls back to all departments if the faculty is not found.
    """
    return FACULTY_DEPARTMENTS.get(faculty, DEPARTMENTS)


def get_faculty_by_department(department: str) -> Optional[str]:
    """Returns the faculty a department belongs to, or None if not found."""
    return next(
        (faculty for faculty, depts in FACULTY_DEPARTMENTS.items() if department in depts),
        None,
    )


def is_valid_department(value: str) -> bool:
    """Returns True if the given string is a valid department name."""
    return value in DEPARTMENTS


def is_valid_faculty(value: str) -> bool:
    """Returns True if the given string is a valid faculty name."""
    return value in FACULTIES


# ─── Public API ──────────────────────────────────────────────────────────────

__all__ = [
    "Faculty",
    "Department",
    "FACULTIES",
    "DEPARTMENTS",
    "FACULTY_DEPARTMENTS",
    "DEPARTMENT_ABBREVIATIONS",
    "FACULTY_ABBREVIATIONS",
    "get_department_abbreviation",
    "get_faculty_abbreviation",
    "list_departments_with_abbreviations",
    "list_faculties_with_abbreviations",
    "get_department_by_abbreviation",
    "get_faculty_by_abbreviation",
    "shorten_department",
    "shorten_faculty",
    "format_name",
    "mask_reg_number",
    "get_departments_by_faculty",
    "get_faculty_by_department",
    "is_valid_department",
    "is_valid_faculty",
]
